// <auto-generated />
using DBVariantDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DBVariantDemo.Migrations
{
    [DbContext(typeof(DBVariantDemoDataContext))]
    [Migration("00000000000000_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBVariantDemo.Data.Variant", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .IsUnicode(true);

                    b.Property<int>("TypeId");

                    b.Property<string>("Value")
                        .IsUnicode(true);

                    b.HasKey("Name");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
